version: '3.3'

services:
  web_test:
    build:
      context: ./web
      dockerfile: Dockerfile-test
      args:
        react_scripts_version: 3.4.1
    command: ["npm", "run", "test", "--", "--coverage"]