version: '3.3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-dev
    ports:
    - '5000:80'
    links:
    - php
    - web

  web:
    build:
      context: ./web
      dockerfile: Dockerfile-dev
      args:
        react_scripts_version: 3.4.1
    env_file: ./web/.env
    stdin_open: true
    restart: always
    volumes:
    - ./web:/app
    - /app/node_modules

  php:
    build: ./php
    env_file: ./php/.env
    volumes:
      - ./php/wp/src:/app/wp
    links:
      - mysql
    expose:
      - 9000

  mysql:
    build: ./mysql
    env_file: ./mysql/.env
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/db-data:/var/lib/mysql
    restart: always
