version: '3.9'
services:
  tests:
    image: ${IMAGE}
    command: ["npm", "run", "test", "--", "--coverage"]
  build-app:
    image: ${IMAGE}
    volumes:
      - ./web/build:/app/build:rw
      - /app/node_modules
    command: ["npm", "run", "build"]
  smokey:
    image: bluehoodie/smoke
    command: -f /test/smoke_test.json -u http://www.arjf.co.uk -t 5
    volumes:
      - .:/test