version: '3.3'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        react_scripts_version: 3.4.1
    env_file: ./web/.env
    restart: "true"
    ports:
      - '81:80'