version: '3.9'
services:
  test:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        react_scripts_version: 5.0.0
    command: ["npm", "run", "test", "--", "--coverage"]
  builds3:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        react_scripts_version: 5.0.0
    volumes:
      - ./web:/app
    command: ["npm", "run", "build"]
  smokey:
    image: bluehoodie/smoke
    command: -f /test/smoke_test.json -u http://www.arjf.co.uk -t 5
    volumes:
      - .:/test