export default {
  REACT_APP_EMAIL_JS_SERVICE_ID: process.env.REACT_APP_EMAIL_JS_SERVICE_ID,
  REACT_APP_EMAIL_JS_TEMPLATE_ID: process.env.REACT_APP_EMAIL_JS_TEMPLATE_ID,
  REACT_APP_EMAIL_JS_USER_ID: process.env.REACT_APP_EMAIL_JS_USER_ID,
  REACT_APP_SENDGRID_API_KEY: process.env.REACT_APP_SENDGRID_API_KEY,
};