FROM node:9.6.1
RUN mkdir /app
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json /app/package.json
RUN npm install --silent  --save-dev && \
    npm install react-scripts@1.1.1 -g --silent && \
    ls node_modules/
COPY . /app