FROM node:12.4.0-alpine
RUN mkdir /app
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json /app/package.json
RUN npm install --silent  --save-dev && \
    npm install react-scripts@1.1.1 -g --silent
COPY . /app