FROM node:14.4.0-stretch
ARG react_scripts_version
RUN mkdir /app
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json /app/package.json
RUN npm install --silent  --save-dev && \
    npm install react-scripts@$react_scripts_version -g --silent
COPY . /app